### ISSUE TITLE
provide tutorial video on ROS

### ISSUE THREAD

**Issue by sabrabano0** [dusty-nv/ros_deep_learning#80] opened 2021-08-07 12:26 UTC
HI 
this is my first experience with  ROS,
i cant found  your tutorial video on this subject similar to before episodes .
i want just use ROS for this project so i don't need to another references.
thank you

**Comment by dusty-nv** [comment] 2021-08-08 00:17
Closing as duplicate of https://github.com/dusty-nv/ros_deep_learning/issues/79

**Closed by dusty-nv** 2021-08-08 00:17 UTC
